## Упражнения по библиотеке Numpy

In [2]:
import numpy as np
import scipy

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
arr = np.random.randint(0, 20, size=10)
print(arr)

mask = (arr >= 3) & (arr <= 8)
arr[mask] *= -1

print(arr)

[ 1 12 11  3 19 16  8  9  8 15]
[ 1 12 11 -3 19 16 -8  9 -8 15]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
arr = np.random.randint(0, 20, size=10)
print(arr)

arr[np.argmax(arr)] = 0

print(arr)

[ 7 11 12  2  4  5  4  5  9  4]
[ 7 11  0  2  4  5  4  5  9  4]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
arr = np.random.randint(0, 20, size=(3, 3))
print(arr)


[[13 14  6]
 [16 13  4]
 [11 15  5]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
arr1 = np.random.randint(0, 20, size=(8, 3))
arr2 = np.random.randint(0, 20, size=(2, 2))
print(arr1)
print(arr2)

result = arr1[np.isin(arr1, arr2)]

print(result)

[[ 5  7 18]
 [ 4  9  3]
 [19 12 19]
 [ 6 19  7]
 [10 12  7]
 [15 15 19]
 [ 4 10  7]
 [ 9  8 11]]
[[ 6  6]
 [11 12]]
[12  6 12 11]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
arr1 = np.array([
    [10, 20, 30],  # Повтор 1
    [5, 5, 5],     # Повтор 1
    [100, 101, 102],
    [1, 2, 3],     # Повтор 1
    [5, 5, 5],     # Повтор 2
    [9, 8, 7],
    [10, 20, 30],  # Повтор 2
    [15, 16, 17],
    [1, 2, 3],     # Повтор 2
    [5, 5, 5]
])

unique_rows_list = [np.unique(arr) for arr in arr1]
mask = np.array([len(u) > 1 for u in unique_rows_list])

result = arr1[mask]

print(result)

[[ 10  20  30]
 [100 101 102]
 [  1   2   3]
 [  9   8   7]
 [ 10  20  30]
 [ 15  16  17]
 [  1   2   3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
arr = np.array([
    [10, 20, 30],  # Повтор 1
    [5, 5, 5],     # Повтор 1
    [100, 101, 102],
    [1, 2, 3],     # Повтор 1
    [5, 5, 5],     # Повтор 2
    [9, 8, 7],
    [10, 20, 30],  # Повтор 2
    [15, 16, 17],
    [1, 2, 3],     # Повтор 2
    [5, 5, 5]
])

res = np.unique(arr, axis=0)
print(res)

[[  1   2   3]
 [  5   5   5]
 [  9   8   7]
 [ 10  20  30]
 [ 15  16  17]
 [100 101 102]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [ ]:
# without numpy
x = [[1, 0, 1], [2, 4, 2], [3, 0, 3], [4, 4, 4]]
res1 = 1

for i in range(len(x[0])):
    res1 *= x[i][i] if x[i][i] != 0 else 1

print(f'Result using only Python: {res1}')

# using NumPy
x = np.array([[1, 0, 1], [2, 4, 2], [3, 0, 3], [4, 4, 4]])
n = 1

diagonal = np.diagonal(x)
filtered_diagonal = diagonal[np.where(diagonal != 0)]
res2 = np.prod(filtered_diagonal)

print(f'Result using only NumPy: {res2}')


Result using only Python: 12
[1 4 3]
Result using only NumPy: 12


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [10]:
# using Python
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
n_x = len(x)
n_y = len(y)
res1 = n_x == n_y

if res1:
    x_unique, y_unique = set(x), set(y)
    x_count, y_count = [x.count(el) for el in x_unique], [y.count(el) for el in y_unique]

    for i in range(len(x_unique)):
        res = x_unique == y_unique and x_count == y_count
        if res:
            continue
        else:
            break

print(f'Result using Python: {res1}')

# using NumPy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

x_unique, x_count = np.unique(x, return_counts=True)
y_unique, y_count = np.unique(y, return_counts=True)

res2 = np.array_equal(x_unique, y_unique) and np.array_equal(x_count, y_count)

print(f'Result using NumPy: {res2}')


Result using Python: True
Result using NumPy: True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль.
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [11]:
# using Python
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max = x[1]
res1 = None

for i in range(1, len(x)):
    if x[i-1] == 0 and x[i] > max:
        res1 = x[i]
        max = x[i]

print(f'Result using Python: {res1}')

# using NumPy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

mask_zeros = x[:-1] == 0

elements_after_zeros = x[1:][mask_zeros]

if elements_after_zeros.size == 0:
    res2 = None
else:
    res2 = np.max(elements_after_zeros)

print(f'Result using NumPy: {res2}')

Result using Python: 5
Result using NumPy: 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [12]:
# using Python
x = [2, 2, 2, 3, 3, 3, 5]
res1_digits = list(set(x))
res1_count = [x.count(el) for el in res1_digits]

print(f'Result using Python: {res1_digits}, {res1_count}')

# your NumPy
x = np.array([2, 2, 2, 3, 3, 3, 5])

res2_digits, res2_count = np.unique(x, return_counts=True)

print(f'Result using NumPy: {res2_digits}, {res2_count}')

Result using Python: [2, 3, 5], [3, 3, 1]
Result using NumPy: [2 3 5], [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [13]:
import numpy as np
import timeit
from scipy.spatial.distance import cdist

# --- Генерация массивов ---
N_X = 5
N_Y = 4
D = 3
np.random.seed(42)
X_np = np.random.uniform(0, 10, size=(N_X, D)).round(2)
Y_np = np.random.uniform(0, 10, size=(N_Y, D)).round(2)
X_list = X_np.tolist()
Y_list = Y_np.tolist()


# --- Метод 1: Чистый Python (Вложенные циклы) ---
def euclidean_distance_python(X, Y):
    N_X = len(X)
    N_Y = len(Y)
    D_matrix = [[0.0] * N_Y for _ in range(N_X)]
    
    for i in range(N_X):
        for j in range(N_Y):
            sum_sq = 0.0
            for k in range(len(X[i])):
                diff = X[i][k] - Y[j][k]
                sum_sq += diff * diff
            D_matrix[i][j] = sum_sq ** 0.5
            
    return np.array(D_matrix)


# --- Метод 2: Только NumPy (Векторизация) ---
def euclidean_distance_numpy(X_np, Y_np):
    X_sq_norms = np.sum(X_np**2, axis=1)[:, np.newaxis]
    Y_sq_norms = np.sum(Y_np**2, axis=1)[np.newaxis, :]
    XY_dot = -2 * np.dot(X_np, Y_np.T)
    D_sq = X_sq_norms + XY_dot + Y_sq_norms
    D_sq[D_sq < 0] = 0
    
    return np.sqrt(D_sq)


# --- Проверка и сравнение ---
print("--- Исходные массивы ---")
print(f"X:\n{X_np}")
print(f"\nY:\n{Y_np}")

# Проверка корректности (должны быть идентичны)
D_py = euclidean_distance_python(X_list, Y_list)
D_np = euclidean_distance_numpy(X_np, Y_np)
D_scipy = cdist(X_np, Y_np, metric='euclidean')

print("\n--- Проверка корректности (Max разница) ---")
print(f"Python vs NumPy: {np.max(np.abs(D_py - D_np)):.2e}")
print(f"NumPy vs SciPy:  {np.max(np.abs(D_np - D_scipy)):.2e}")

# Измерение времени (используем более крупный массив для значимого сравнения)
N_BIG = 1000
D_BIG = 10
X_BIG = np.random.rand(N_BIG, D_BIG)
Y_BIG = np.random.rand(N_BIG, D_BIG)
X_BIG_list = X_BIG.tolist()
Y_BIG_list = Y_BIG.tolist()

num_runs = 5

time_py = timeit.timeit(lambda: euclidean_distance_python(X_BIG_list, Y_BIG_list), number=1) * 1e3
time_np = timeit.timeit(lambda: euclidean_distance_numpy(X_BIG, Y_BIG), number=num_runs) / num_runs * 1e3
time_scipy = timeit.timeit(lambda: cdist(X_BIG, Y_BIG, metric='euclidean'), number=num_runs) / num_runs * 1e3

print("\n--- Сравнение производительности (1000x1000x10) ---")
print(f"1. Чистый Python (1 запуск):    {time_py:.2f} мс")
print(f"2. NumPy (векторизация):        {time_np:.2f} мс")
print(f"3. SciPy cdist (оптимизация C): {time_scipy:.2f} мс")
print("-" * 40)
print(f"NumPy быстрее Python примерно в {time_py / time_np:.0f} раз")

--- Исходные массивы ---
X:
[[3.75 9.51 7.32]
 [5.99 1.56 1.56]
 [0.58 8.66 6.01]
 [7.08 0.21 9.7 ]
 [8.32 2.12 1.82]]

Y:
[[1.83 3.04 5.25]
 [4.32 2.91 6.12]
 [1.39 2.92 3.66]
 [4.56 7.85 2.  ]]

--- Проверка корректности (Max разница) ---
Python vs NumPy: 2.66e-15
NumPy vs SciPy:  2.66e-15

--- Сравнение производительности (1000x1000x10) ---
1. Чистый Python (1 запуск):    1469.31 мс
2. NumPy (векторизация):        24.67 мс
3. SciPy cdist (оптимизация C): 8.87 мс
----------------------------------------
NumPy быстрее Python примерно в 60 раз


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [14]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [15]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [16]:
avg_calories = round(np.average(calorie_stats), 2)

print(avg_calories)

106.88


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [17]:
calorie_stats_sorted = np.sort(calorie_stats)

print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [18]:
median_calories = np.median(calorie_stats_sorted)

print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [19]:
nth_percentile = None
q = 0 

print("--- Расчет процентилей (шаг 1%) ---")

while q <= 100:
    current_value = np.percentile(calorie_stats_sorted, q)
    
    print(f"P_{q:02d}% = {current_value:.2f} кал")
    
    if current_value > 60:
        nth_percentile = q
        print("-" * 35)
        print(f"Условие выполнено: {current_value:.2f} кал > 60 кал")
        break 
        
    q += 1

--- Расчет процентилей (шаг 1%) ---
P_00% = 50.00 кал
P_01% = 50.00 кал
P_02% = 50.00 кал
P_03% = 55.60 кал
P_04% = 70.00 кал
-----------------------------------
Условие выполнено: 70.00 кал > 60 кал


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [20]:
mask = (calorie_stats_sorted > 60)
count_more_than_60 = np.sum(mask)
n = len(calorie_stats_sorted)
more_calories = (count_more_than_60 / n) * 100

print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [21]:
calorie_std = np.std(calorie_stats_sorted)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [22]:
"""
    Стандартное отклонение 19.36 кал подтверждает, что в наборе данных очень большой разброс. Это означает, что конкурентная среда сильно различается по калорийности, 
    и вам нужно использовать это большое отклонение, чтобы подчеркнуть, насколько сильно ваш продукт отличается от рыночной нормы.
"""

'\n    Стандартное отклонение 19.36 кал подтверждает, что в наборе данных очень большой разброс. Это означает, что конкурентная среда сильно различается по калорийности, \n    и вам нужно использовать это большое отклонение, чтобы подчеркнуть, насколько сильно ваш продукт отличается от рыночной нормы.\n'